Repository suratu-io/curl-telegram-bot, pull requests merged in 2019-08, with the labels that each got.

#1 feat (general-logic): implement basic comands handle
  app/main.go
Labels: enhancement

#3 docs: add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#17 fix: Add a proper URL parsing
  app/commands/request/arguments/service.go
Labels: bug

#19 feat: add .editorconfig
  .editorconfig
  app/commands/callback_map_model.go
  app/commands/request/arguments/service.go
  app/commands/request/model.go
  app/config/model.go
Labels: ci/cd, enhancement

#20 feat: add stale bot
  .github/stale.yml
Labels: ci/cd, enhancement

#22 docs: add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#23 ci: add lint and test ci configs (#10)
  .codecov.yml
  .gitignore
  .travis.yml
  README.md
  app/bot/service.go
  app/commands/request/arguments/service.go
  app/config/model.go
  app/main.go
  scripts/checker.sh
  scripts/hooks/pre-commit.sh
  scripts/init.sh
  scripts/lint.sh
  scripts/test.sh
Labels: ci/cd
